version: "3.8"

services:
  movie_service:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./:/app/
#    networks:
#      - movies_network
#      - movies_db_network
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://movies:movies@movie_db/movie_db_dev
#      - 'postgresql://movies:movies@localhost:5432/movies_db'
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      - movie_db

  movie_db:
    image: postgres
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
#    networks:
#      - movies_db_network
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movie_db_dev

volumes:
  postgres_data_movie:

#networks:
#  movies_network:
#    external: true
#  movies_db_network:
