version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
        - ./data/:/var/lib/rabbitmq/
        - ./log/:/var/log/rabbitmq
#    networks:
#      - movies_network

#  listener:
#        build: .
#        volumes:
#            - .:/code
#        command: python listener.py
#        depends_on:
#            - rabbitmq


#networks:
#  movies_network:
#    external: true