version: "3.8"

services:
  cast_service:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8002
    volumes:
      - ./:/app/
    networks:
      - movies_network
      - casts_db_network
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URI=postgresql://cast:cast@cast_db/cast_db_dev
    depends_on:
      - cast_db

  cast_db:
    image: postgres
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    networks:
      - casts_db_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cast
      - POSTGRES_PASSWORD=cast
      - POSTGRES_DB=cast_db_dev

volumes:
  postgres_data_cast:

networks:
  movies_network:
    external: true
  casts_db_network: